# Generated by Django 2.2.1 on 2019-07-10 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=20)),
                ('state_code', models.IntegerField()),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('po_no', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Customer')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('firm_name', models.CharField(max_length=50)),
                ('firm_address', models.CharField(max_length=80)),
                ('mobile_number', models.IntegerField()),
                ('gst_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=15)),
                ('bank_account_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=25)),
                ('bank_ifsc_code', models.CharField(max_length=15)),
                ('bank_branch_address', models.CharField(max_length=80)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsncode', models.IntegerField(blank=True)),
                ('item_name', models.CharField(max_length=20)),
                ('gst', models.FloatField(max_length=2)),
                ('mrp', models.FloatField(blank=True, max_length=15)),
                ('buy_price', models.FloatField(blank=True, max_length=15)),
                ('sell_price', models.FloatField(max_length=15)),
                ('unit', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Category')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default=0)),
                ('rate', models.FloatField(max_length=15)),
                ('quantity', models.IntegerField(default=1)),
                ('discount', models.FloatField(blank=True, default=0, max_length=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Category')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.CustomerInvoice')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Item')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
